docker pull  ibmcom/metering-reader:2.1.0.2
docker pull  ibmcom/kubernetes:v1.9.1
docker pull  ibmcom/nginx-ingress-controller:0.9.0
docker pull  ibmcom/calico-node:v2.6.6
docker pull  ibmcom/icp-initcontainer:1.0.0
docker pull  ibmcom/calico-cni:v1.11.2
docker pull  ibmcom/node-exporter:v0.15.2
docker pull  ibmcom/filebeat:5.5.1
docker pull  ibmcom/defaultbackend:1.2
docker pull  ibmcom/pause:3.0
