docker pull  ibmcom/metering-reader:2.1.0.2
docker pull  ibmcom/kubernetes:v1.9.1
docker pull  ibmcom/icp-router:2.2.0
docker pull  ibmcom/metering-data-manager:2.1.0.2
docker pull  ibmcom/metering-ui:2.1.0.2
docker pull  ibmcom/metering-server:2.1.0.2
docker pull  ibmcom/calico-node:v2.6.6
docker pull  ibmcom/kube-state-metrics:v1.2.0
docker pull  ibmcom/alertmanager:v0.13.0
docker pull  ibmcom/icp-initcontainer:1.0.0
docker pull  ibmcom/calico-cni:v1.11.2
docker pull  ibmcom/grafana:4.6.3
docker pull  ibmcom/node-exporter:v0.15.2
docker pull  ibmcom/prometheus:v2.0.0
docker pull  ibmcom/indices-cleaner:0.2
docker pull  ibmcom/curl:3.6
docker pull  ibmcom/kibana:5.5.1
docker pull  ibmcom/filebeat:5.5.1
docker pull  ibmcom/logstash:5.5.1
docker pull  ibmcom/elasticsearch:5.5.1
docker pull  ibmcom/k8s-dns-sidecar:1.14.4
docker pull  ibmcom/k8s-dns-kube-dns:1.14.4
docker pull  ibmcom/k8s-dns-dnsmasq-nanny:1.14.4
docker pull  ibmcom/configmap-reload:v0.1
docker pull  ibmcom/collectd-exporter:0.3.1
docker pull  ibmcom/pause:3.0
