########################################################################################
### echo -n "test-user" | base64 
### dGVzdC11c2Vy
###
### echo -n "test-pass" | base64 
### dGVzdC1wYXNz
###
### kubectl apply -f test-secret.yaml
########################################################################################
---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
data:
  username: dGVzdC11c2Vy
  password: dGVzdC1wYXNz
---
