docker pull  ibmcom/icp-helm-rudder:2.1.0.2
docker pull  ibmcom/iam-policy-decision:2.1.0.2
docker pull  ibmcom/icp-image-manager:2.2.1
docker pull  ibmcom/icp-platform-api:2.1.0.2
docker pull  ibmcom/iam-policy-administration:2.1.0.2
docker pull  ibmcom/iam-token-service:2.1.0.2
docker pull  ibmcom/icp-platform-ui:2.1.0.2
docker pull  ibmcom/icp-platform-auth:2.1.0.2
docker pull  ibmcom/icp-platform-deploy:2.1.0.2
docker pull  ibmcom/icp-identity-provider:2.1.0.2
docker pull  ibmcom/icp-identity-manager:2.1.0.2
docker pull  ibmcom/icp-catalog-ui:2.1.0.2
docker pull  ibmcom/icp-helm-api:2.1.0.2
docker pull  ibmcom/icp-helm-repo:2.1.0.2
docker pull  ibmcom/tiller:v2.7.2-icp
docker pull  ibmcom/metering-reader:2.1.0.2
docker pull  ibmcom/kubernetes:v1.9.1
docker pull  ibmcom/icp-management-ingress:2.2.0
docker pull  ibmcom/unified-router:2.2.0
docker pull  ibmcom/calico-node:v2.6.6
docker pull  ibmcom/calico-kube-controllers:v1.0.3
docker pull  ibmcom/etcd:v3.2.14
docker pull  ibmcom/calico-cni:v1.11.2
docker pull  ibmcom/calico-ctl:v1.6.3
docker pull  ibmcom/icp-datastore:1.1.0
docker pull  ibmcom/node-exporter:v0.15.2
docker pull  ibmcom/service-catalog-service-catalog:v0.1.2
docker pull  ibmcom/rescheduler:v0.5.2
docker pull  ibmcom/filebeat:5.5.1
docker pull  ibmcom/heapster:v1.4.0
docker pull  ibmcom/mariadb:10.1.16
docker pull  ibmcom/registry:2
docker pull  ibmcom/pause:3.0
