---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-bpd-appdata-pv
   labels:
       type: cam-bpd-appdata
spec:
   capacity:
      storage: 15Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   glusterfs:
      endpoints: glusterfs-lxd     ## Update endpoint as per your configuration
      path: vol1                   ## Update path as per your configuration
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-mongo-pv
   labels:
       type: cam-mongo
spec:
   capacity:
      storage: 15Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   glusterfs:
      endpoints: glusterfs-lxd   ## Update endpoint as per your configuration
      path: vol2                 ## Update path as per your configuration
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-logs-pv
   labels:
       type: cam-logs
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   glusterfs:
      endpoints: glusterfs-lxd   ## Update endpoint as per your configuration
      path: vol3                 ## Update path as per your configuration
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-terraform-pv
   labels:
       type: cam-terraform
spec:
   capacity:
      storage: 15Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   glusterfs:
      endpoints: glusterfs-lxd  ## Update endpoint as per your configuration
      path: vol4                ## Update path as per your configuration
---
