---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-bpd-appdata-pv
   labels:
       type: cam-bpd-appdata
spec:
   capacity:
      storage: 15Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      server: NFS_SERVER_IP_ADDRESS
      path: /nfs/vol1
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-mongo-pv
   labels:
       type: cam-mongo
spec:
   capacity:
      storage: 15Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      server: NFS_SERVER_IP_ADDRESS
      path: /nfs/vol2
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-logs-pv
   labels:
       type: cam-logs
spec:
   capacity:
      storage: 10Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      server: NFS_SERVER_IP_ADDRESS
      path: /nfs/vol3
---
apiVersion: v1
kind: PersistentVolume
metadata:
   name: cam-terraform-pv
   labels:
       type: cam-terraform
spec:
   capacity:
      storage: 15Gi
   accessModes:
      - ReadWriteMany
   persistentVolumeReclaimPolicy: Retain
   nfs:
      server: NFS_SERVER_IP_ADDRESS
      path: /nfs/vol4
